# Jekyll configuration for GitHub Pages
# This enables proper MIME types and CORS headers

include:
  - data
  - audio
  - scripts

# Set proper content types
defaults:
  - scope:
      path: "data"
    values:
      layout: null
  - scope:
      path: "audio"
    values:
      layout: null

